---

- name: Enable repositories required by AAP 2.5 Installation
  community.general.rhsm_repository:
    name: 
      - ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - rhel-9-for-x86_64-baseos-rpms
    state: enabled
  become: yes

- name: Extract AAP 2.5 setup tarball
  ansible.builtin.unarchive:
    src: files/ansible-automation-platform-setup-2.5-17.tar.gz
    dest: /opt
    remote_src: no
    mode: '0755'
    extra_opts: [--overwrite]
  become: yes

- name: Generate dynamic AAP inventory
  ansible.builtin.template:
    src: inventory.j2
    dest: /opt/ansible-automation-platform-setup-2.5-17/inventory
    mode: '0644'
  become: yes

- name: Installing AAP 2.5
  ansible.builtin.shell: |
    /opt/ansible-automation-platform-setup-2.5-17/setup.sh
  args:
    chdir: /opt/ansible-automation-platform-setup-2.5-17
    executable: /bin/bash
  environment:
    PYTHONUNBUFFERED: "1"
    ANSIBLE_FORCE_COLOR: "True"
  async: 3600
  poll: 0
  become: yes

- name: Monitoring the Installation Process
  debug:
    msg: TO MONITORING THE INSTALLATION PROCESS, RUN ->> sudo tail -f /opt/ansible-automation-platform-setup-2.5-17/setup.log
