---
- name: Deploy lab VMs
  hosts: localhost
  gather_facts: false
  become: yes
  vars:
    target_env: "{{ target_env }}" # use aap or ocp
    vms: "{{ vms_all[target_env] }}"

  roles:
    - homelab.mylab.deploy_vms

  tasks:

    - name: Add each VM to dynamic inventory
      ansible.builtin.add_host:
        name: "{{ item.ip }}"
        groups: vms
        ansible_user: root
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      loop: "{{ vms }}"
      loop_control:
        loop_var: item

- name: Registering hosts to Red Hat Satellite
  hosts: vms
  gather_facts: false
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.9

  tasks:

    - name: Wait until VM SSH is ready
      ansible.builtin.wait_for_connection:
        delay: 20
        timeout: 10

    - name: Registering ...
      ansible.builtin.shell: sh /root/register-satellite.sh
