---
- name: Deploy lab VMs
  hosts: localhost
  gather_facts: false
  become: yes
  vars:
    target_env: "{{ target_env }}" # use aap or ocp
    vms: "{{ vms_all[target_env] }}"

  roles:
    - homelab.mylab.deploy_vms

  tasks:

    - name: Add each VM to dynamic inventory
      ansible.builtin.add_host:
        name: "{{ item.ip }}"
        groups: vms
        ansible_user: root
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      loop: "{{ vms }}"
      loop_control:
        loop_var: item

- name: Registering hosts to CDN
  hosts: vms
  gather_facts: false
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  vars_files:
    - ../roles/deploy_vms/vars/main.yml

  tasks:

    - name: Wait until VM SSH is ready
      ansible.builtin.wait_for_connection:
        delay: 20
        timeout: 10

    - name: Registering as user {{ registry_user }}.
      community.general.redhat_subscription:
        state: present
        username: "{{ registry_user }}"
        password: "{{ registry_pass }}"

    - name: Enable repositories required by AAP 2.5 Installation
      community.general.rhsm_repository:
        name:
          - ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms
          - rhel-9-for-x86_64-appstream-rpms
          - rhel-9-for-x86_64-baseos-rpms
        state: enabled
      become: yes
      when: target_env == aap
