---
# Provision step
- ansible.builtin.import_playbook: deployvms.yml
  tags:
    - deployvms

# AAP 2.7 deployment
- ansible.builtin.import_playbook: aap27.yml
  tags:
    - aap27

# OpenShift 4 deployment
- ansible.builtin.import_playbook: ocp4.yml
  tags:
    - ocp4

